import type { PricingConfig } from "./pricing-types";

export const defaultPricingConfig: PricingConfig = {
  singleLead: {
    basePrice: 120,
    currency: "EUR",
  },
  volumeTiers: [
    {
      quantity: 1,
      totalPrice: 120,
      perLeadPrice: 120,
      savings: 0,
      badge: null,
      discountLabel: "Keine Ermäßigung",
    },
    {
      quantity: 5,
      totalPrice: 550,
      perLeadPrice: 110,
      savings: 50,
      badge: "Beliebt",
      discountLabel: null,
    },
    {
      quantity: 10,
      totalPrice: 1000,
      perLeadPrice: 100,
      savings: 200,
      badge: "Bestes Preis-Leistungs-Verhältnis",
      discountLabel: null,
    },
    {
      quantity: 25,
      totalPrice: 2250,
      perLeadPrice: 90,
      savings: 750,
      badge: "Für aktive Vertriebsteams",
      discountLabel: null,
    },
    {
      quantity: 50,
      totalPrice: 4000,
      perLeadPrice: 80,
      savings: 2000,
      badge: "Professional",
      discountLabel: null,
    },
    {
      quantity: 100,
      totalPrice: 7000,
      perLeadPrice: 70,
      savings: 5000,
      badge: "Enterprise",
      discountLabel: null,
    },
  ],
  categories: [
    { slug: "unternehmensberatung", name: "Unternehmensberatung", basePrice: 120 },
    { slug: "foerdermittelberatung", name: "Fördermittelberatung", basePrice: 120 },
    { slug: "digitalisierung", name: "Digitalisierung", basePrice: 120 },
    { slug: "finanzierung", name: "Finanzierung", basePrice: 120 },
    { slug: "ma", name: "M&A", basePrice: 120 },
  ],
  exclusive: {
    basePrice: 180,
    exampleLead: {
      category: "Fördermittelberatung",
      age: "1 Stunde",
      score: 96,
      price: 180,
    },
  },
  subscriptions: [
    {
      slug: "zugang",
      name: "Zugang",
      monthlyPrice: 390,
      includedLeads: 3,
      badge: null,
      featured: false,
      description: "Drei frische Leads im Monat. Kein Dashboard, keine Extras.",
      features: [
        "3 Leads pro Monat",
        "Kontakt und Anfrage enthalten",
        "Monatlich kündbar",
        "Keine Rückerstattung",
      ],
      cta: "Zugang wählen",
    },
    {
      slug: "atelier",
      name: "Atelier",
      monthlyPrice: 980,
      includedLeads: 10,
      badge: "Empfohlen",
      featured: true,
      description: "Zehn Leads im Monat für laufende Nachfrage. Kein Dashboard, keine Exklusiv-Leads.",
      features: [
        "10 Leads pro Monat",
        "Kontakt und Anfrage enthalten",
        "Monatlich kündbar",
        "Keine Rückerstattung",
      ],
      cta: "Atelier wählen",
    },
    {
      slug: "kanzlei",
      name: "Kanzlei",
      monthlyPrice: 2400,
      includedLeads: 30,
      badge: "Für Teams",
      featured: false,
      description: "Dreißig Leads im Monat für Teams. Nur Leads, keine Plattform-Extras.",
      features: [
        "30 Leads pro Monat",
        "Kontakt und Anfrage enthalten",
        "Monatlich kündbar",
        "Keine Rückerstattung",
      ],
      cta: "Partnerschaft anfragen",
    },
  ],
  settings: {
    noSubscriptionRequired: false,
  },
};
