import type { PricingConfig } from "./pricing-types";

export const defaultPricingConfig: PricingConfig = {
  singleLead: {
    basePrice: 120,
    currency: "EUR",
  },
  volumeTiers: [
    {
      quantity: 1,
      totalPrice: 120,
      perLeadPrice: 120,
      savings: 0,
      badge: null,
      discountLabel: "Keine Ermäßigung",
    },
    {
      quantity: 5,
      totalPrice: 550,
      perLeadPrice: 110,
      savings: 50,
      badge: "Beliebt",
      discountLabel: null,
    },
    {
      quantity: 10,
      totalPrice: 1000,
      perLeadPrice: 100,
      savings: 200,
      badge: "Bestes Preis-Leistungs-Verhältnis",
      discountLabel: null,
    },
    {
      quantity: 25,
      totalPrice: 2250,
      perLeadPrice: 90,
      savings: 750,
      badge: "Für aktive Vertriebsteams",
      discountLabel: null,
    },
    {
      quantity: 50,
      totalPrice: 4000,
      perLeadPrice: 80,
      savings: 2000,
      badge: "Professional",
      discountLabel: null,
    },
    {
      quantity: 100,
      totalPrice: 7000,
      perLeadPrice: 70,
      savings: 5000,
      badge: "Enterprise",
      discountLabel: null,
    },
  ],
  categories: [
    { slug: "unternehmensberatung", name: "Unternehmensberatung", basePrice: 120 },
    { slug: "foerdermittelberatung", name: "Fördermittelberatung", basePrice: 120 },
    { slug: "digitalisierung", name: "Digitalisierung", basePrice: 130 },
    { slug: "finanzierung", name: "Finanzierung", basePrice: 150 },
    { slug: "ma", name: "M&A", basePrice: 250 },
    { slug: "exklusiv", name: "Exklusive Leads", basePrice: 180 },
  ],
  exclusive: {
    basePrice: 180,
    exampleLead: {
      category: "Fördermittelberatung",
      age: "1 Stunde",
      score: 96,
      price: 180,
    },
  },
  subscriptions: [
    {
      slug: "zugang",
      name: "Zugang",
      monthlyPrice: 390,
      includedLeads: 3,
      badge: null,
      featured: false,
      description: "Für Berater, die Leiter regelmäßig nutzen möchten, ohne großes Paket.",
      features: [
        "3 Leads pro Monat inklusive",
        "Vollständiger Dashboard-Zugang",
        "Lead-Alter und Score sichtbar",
        "Kategorien nach Angebot filtern",
        "Monatlich kündbar",
      ],
      cta: "Zugang wählen",
    },
    {
      slug: "atelier",
      name: "Atelier",
      monthlyPrice: 980,
      includedLeads: 10,
      badge: "Empfohlen",
      featured: true,
      description: "Für aktive Mandate: kontinuierliche Anfragen mit klarer Priorität.",
      features: [
        "10 Leads pro Monat inklusive",
        "24-Stunden-Fenster auf exklusive Leads",
        "Priorisierte Branchenfilter",
        "Mengenrabatt auf zusätzliche Leads",
        "Persönlicher Ansprechpartner",
      ],
      cta: "Atelier wählen",
    },
    {
      slug: "kanzlei",
      name: "Kanzlei",
      monthlyPrice: 2400,
      includedLeads: 30,
      badge: "Für Teams",
      featured: false,
      description: "Für Vertriebsteams, die frische Nachfrage fest in den Alltag holen.",
      features: [
        "30 Leads pro Monat inklusive",
        "Bevorzugter Zugang zu exklusiven Leads",
        "Feste geografische Aussteuerung",
        "Gemeinsames Team-Dashboard",
        "Quartalsgespräch zur Qualität",
      ],
      cta: "Partnerschaft anfragen",
    },
  ],
  settings: {
    noSubscriptionRequired: false,
  },
};
